name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Run Type Check, Linters & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Check linting
        run: bun run lint

      # - name: Run tests
      #   run: bun test
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}